### PR TITLE
add self update option

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
### Proposed Changes

```console
UPDATE:
   -up, -update                 update mapcidr to the latest version
   -duc, -disable-update-check  disable automatic update check
```

### Reference
- Reference: https://github.com/projectdiscovery/tlsx/blob/8038ac06765d490210aa8bf753f44758a653b39f/cmd/tlsx/main.go#L125

### CODE REVIEW

**Comment by RamanaReddy0M** [comment]
```console
✗ ./mapcidr -up

                   ____________  ___    
  __ _  ___ ____  / ___/  _/ _ \/ _ \   
 /  ' \/ _ '/ _ \/ /___/ // // / , _/   
/_/_/_/\_,_/ .__/\___/___/____/_/|_| v1.1.0
          /_/                                                            

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
6.47 MiB / 6.47 MiB [--------------------------------------------------------] 100.00% 10.65 MiB p/s

[INF] mapcidr sucessfully updated 1.0.0 -> 1.1.0 (latest)

  ## What's Changed                                                           
                                                                              
  • Updated code to implement DefaultClient in asn package by @xm1k3 in       
  https://github.com/projectdiscovery/mapcidr/pull/144                        
  • Updated code to use utils helpers libraries by @edoardottt in             
  https://github.com/projectdiscovery/mapcidr/pull/124                        
  • Added mapcidr as code integration test by @LuitelSamikshya in             
  https://github.com/projectdiscovery/mapcidr/pull/127                        
  • Added autorelease gh workflow by @tarunKoyalwar in                        
  https://github.com/projectdiscovery/mapcidr/pull/143                        
                                                                              
  ## New Contributors                                                         
                                                                              
  • @edoardottt made their first contribution in                              
  https://github.com/projectdiscovery/mapcidr/pull/124                        
  • @tarunKoyalwar made their first contribution in                           
  https://github.com/projectdiscovery/mapcidr/pull/143                        
  • @xm1k3 made their first contribution in                                   
  https://github.com/projectdiscovery/mapcidr/pull/144                        
                                                                              
  Full Changelog:                                                             
  https://github.com/projectdiscovery/mapcidr/compare/v1.0.3...v1.1.0

```

**Review by tarunKoyalwar — APPROVED** [review]
lgtm !

```console
./mapcidr   

                   ____________  ___    
  __ _  ___ ____  / ___/  _/ _ \/ _ \   
 /  ' \/ _ '/ _ \/ /___/ // // / , _/   
/_/_/_/\_,_/ .__/\___/___/____/_/|_| v1.1.0
          /_/                                                     	 

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current mapcidr version v1.1.0 (latest)
[FTL] no input provided

```

**Comment by tarunKoyalwar** [comment]
@ehsandeep  should we keep/remove the `Use with caution` statement ? we don't use it anymore even in `nuclei`

**Comment by ehsandeep** [comment]
> @ehsandeep should we keep/remove the `Use with caution` statement ? we don't use it anymore even in `nuclei`

will remove with the new release.

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
